# Generated by Django 3.2.7 on 2021-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrottenMovie',
            fields=[
                ('movie_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Movie Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('gross_sales', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('approval_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approval Percentage')),
            ],
        ),
    ]
