# Generated by Django 3.2.7 on 2021-09-13 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrottenMovie',
            fields=[
                ('movie_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Movie Id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('genre', models.CharField(max_length=255, unique=True, verbose_name='Genre')),
                ('year', models.CharField(max_length=255, unique=True, verbose_name='Year')),
                ('gross_sales', models.CharField(max_length=255, unique=True, verbose_name='Gross Sales')),
            ],
        ),
    ]
